title:              Mat Loughnane
email:              mat@hexastudios.co
description:        A Blog Theme by Start Bootstrap
author:             Mat Loughnane
baseurl:            ""
url:                "https://matloughnane.github.io"

# Social Profiles
twitter_username:   mat_loughnane
github_username:    matloughnane
facebook_username:  mat.loughnane
linkedin_username:  mat.loughnane

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
